// Generated by LiveScript 1.2.0
var Padnews;
Padnews = require('./lib/padnews');
new Padnews('sgyfCRGiBZC').run(5000, function(event, msg){
  var i$, ref$, len$, p;
  console.log(event + " " + msg.time + " [" + (msg.location || '公開') + "]");
  for (i$ = 0, len$ = (ref$ = msg.content).length; i$ < len$; ++i$) {
    p = ref$[i$];
    console.log(p + "");
  }
  return console.log('');
});