// Generated by LiveScript 1.2.0
var request, split, deepDiff, Padnews;
request = require('request');
split = require('split');
deepDiff = require('deep-diff');
Padnews = (function(){
  Padnews.displayName = 'Padnews';
  var prototype = Padnews.prototype, constructor = Padnews;
  function Padnews(id){
    this.id = id;
    this.news = [];
  }
  prototype.separator = /(\r?\n|<\/p>|<p>)/;
  prototype.match = /\s*(\d?\d:\S\S)\s*(?:\[\s*(.+)\s*\])?\s*(.+)\s*/;
  prototype.get = function(cb){
    var last, result, this$ = this;
    result = [];
    return request.get("https://g0v.hackpad.com/ep/pad/static/" + this.id).pipe(split(this.separator)).on('data', function(it){
      var news;
      news = this$.match.exec(it);
      if (news) {
        last = {
          time: news[1],
          location: news[2] || '',
          content: [news[3]]
        };
        return result.push(last);
      } else if (it.length && !/(\r?\n|^<.*>$)/.test(it)) {
        return last != null ? last.content.push(it) : void 8;
      }
    }).on('end', function(){
      return typeof cb === 'function' ? cb(result.reverse()) : void 8;
    });
  };
  prototype.run = function(delay, onMsg){
    var updateLoop, this$ = this;
    (updateLoop = function(){
      return this$.get(function(news){
        var newEntries, i, current, prev, content, ds;
        newEntries = [];
        for (i in news) {
          current = news[i];
          prev = this$.news[i];
          if (prev) {
            ds = deepDiff.diff(current, prev);
            if (!ds) {
              continue;
            }
            import$(prev, current);
            if (typeof onMsg === 'function') {
              onMsg('update', current, ds);
            }
            break;
          } else {
            newEntries.push(current);
            if (typeof onMsg === 'function') {
              onMsg('create', current);
            }
          }
        }
        Array.prototype.push.apply(this$.news, newEntries);
        return setTimeout(updateLoop, delay);
      });
    })();
  };
  return Padnews;
}());
module.exports = Padnews;
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}